// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & { // Group
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never
  } & { // Other fields
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Hero Title field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We Navigate the digital landscape for success
   * - **API ID Path**: about.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField

  /**
   * Hero Description field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Our digital marketing agency helps businesses...
   * - **API ID Path**: about.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField

  /**
   * Hero Button Text field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book a consultation
   * - **API ID Path**: about.hero_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_button_text: prismic.KeyTextField
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, 'about', Lang>

/**
 * Item in *Blog Post → Tags*
 */
export interface BlogPostDocumentDataTagsItem {
  /**
   * Tag field in *Blog Post → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Code
   * - **API ID Path**: blog_post.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField
}

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Guardian of the Digital Realm: Web Security
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the blog post...
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>

  /**
   * Author Name field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jese Leos
   * - **API ID Path**: blog_post.author_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField

  /**
   * Author Avatar field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author_avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_avatar: prismic.ImageField<never>

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select publish date
   * - **API ID Path**: blog_post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField

  /**
   * Badge Type field in *Blog Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Article
   * - **API ID Path**: blog_post.badge_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  badge_type: prismic.SelectField<'Tutorial' | 'Article', 'filled'>

  /**
   * Tags field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<BlogPostDocumentDataTagsItem>>

  /**
   * Content field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your blog post content here...
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >

/**
 * Item in *Homepage → Services List → Benefits*
 */
export interface HomepageDocumentDataServicesBenefitsItem {
  /**
   * Benefit field in *Homepage → Services List → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Increased organic traffic
   * - **API ID Path**: homepage.services[].benefits[].benefit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  benefit: prismic.KeyTextField
}

/**
 * Item in *Homepage → Services List*
 */
export interface HomepageDocumentDataServicesItem {
  /**
   * Service Name field in *Homepage → Services List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search engine optimization
   * - **API ID Path**: homepage.services[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField

  /**
   * Service Subtitle field in *Homepage → Services List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Boost your online visibility
   * - **API ID Path**: homepage.services[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField

  /**
   * Icon (Emoji) field in *Homepage → Services List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 🔎
   * - **API ID Path**: homepage.services[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField

  /**
   * Service Image field in *Homepage → Services List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>

  /**
   * Background Color field in *Homepage → Services List*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: bg-gray-light
   * - **API ID Path**: homepage.services[].background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    'bg-gray-light' | 'bg-primary' | 'bg-dark',
    'filled'
  >

  /**
   * Title Background Color field in *Homepage → Services List*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: bg-primary
   * - **API ID Path**: homepage.services[].title_background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_background_color: prismic.SelectField<
    'bg-primary' | 'bg-white',
    'filled'
  >

  /**
   * What we offer field in *Homepage → Services List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We optimize your website...
   * - **API ID Path**: homepage.services[].what_we_offer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  what_we_offer: prismic.RichTextField

  /**
   * CTA Text field in *Homepage → Services List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get SEO Audit
   * - **API ID Path**: homepage.services[].cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField

  /**
   * CTA Link field in *Homepage → Services List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to service page...
   * - **API ID Path**: homepage.services[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField

  /**
   * Benefits field in *Homepage → Services List*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[].benefits[]
   * - **Documentation**: https://prismic.io/docs/fields/group
   */
  benefits: prismic.GroupField<
    Simplify<HomepageDocumentDataServicesBenefitsItem>
  >
}

/**
 * Item in *Homepage → Case Studies List*
 */
export interface HomepageDocumentDataCaseStudiesItem {
  /**
   * Description field in *Homepage → Case Studies List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: For a local restaurant...
   * - **API ID Path**: homepage.case_studies[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Link field in *Homepage → Case Studies List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Learn more link...
   * - **API ID Path**: homepage.case_studies[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField

  /**
   * Link Label field in *Homepage → Case Studies List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn more
   * - **API ID Path**: homepage.case_studies[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField
}

/**
 * Item in *Homepage → Process Steps*
 */
export interface HomepageDocumentDataProcessStepsItem {
  /**
   * Step Number field in *Homepage → Process Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01
   * - **API ID Path**: homepage.process_steps[].number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField

  /**
   * Step Title field in *Homepage → Process Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Consultation
   * - **API ID Path**: homepage.process_steps[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *Homepage → Process Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: During the initial consultation...
   * - **API ID Path**: homepage.process_steps[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField
}

/**
 * Item in *Homepage → Team Members*
 */
export interface HomepageDocumentDataTeamMembersItem {
  /**
   * Name field in *Homepage → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: John Smith
   * - **API ID Path**: homepage.team_members[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField

  /**
   * Role field in *Homepage → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: CEO and Founder
   * - **API ID Path**: homepage.team_members[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField

  /**
   * Experience field in *Homepage → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 10+ years...
   * - **API ID Path**: homepage.team_members[].experience
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  experience: prismic.KeyTextField

  /**
   * Avatar field in *Homepage → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.team_members[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>
}

/**
 * Item in *Homepage → Testimonials List*
 */
export interface HomepageDocumentDataTestimonialsItem {
  /**
   * Quote field in *Homepage → Testimonials List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We have been working...
   * - **API ID Path**: homepage.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField

  /**
   * Author Name field in *Homepage → Testimonials List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: John Smith
   * - **API ID Path**: homepage.testimonials[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField

  /**
   * Author Position field in *Homepage → Testimonials List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Marketing Director at XYZ Corp
   * - **API ID Path**: homepage.testimonials[].position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField
}

/**
 * Item in *Homepage → Client Logos*
 */
export interface HomepageDocumentDataClientLogosItem {
  /**
   * Client Logo field in *Homepage → Client Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.client_logos[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>

  /**
   * Client Name field in *Homepage → Client Logos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company Name
   * - **API ID Path**: homepage.client_logos[].client_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Navigating the digital landscape...
   * - **API ID Path**: homepage.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField

  /**
   * Hero Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Our digital marketing agency helps...
   * - **API ID Path**: homepage.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField

  /**
   * Hero Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book a consultation
   * - **API ID Path**: homepage.hero_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_button_text: prismic.KeyTextField

  /**
   * Hero Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never> /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Services
   * - **API ID Path**: homepage.services_title
   * - **Tab**: Services
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  services_title: prismic.RichTextField

  /**
   * Section Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: At our digital marketing agency...
   * - **API ID Path**: homepage.services_description
   * - **Tab**: Services
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  services_description: prismic.RichTextField

  /**
   * Services List field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[]
   * - **Tab**: Services
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<Simplify<HomepageDocumentDataServicesItem>> /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Case Studies
   * - **API ID Path**: homepage.case_studies_title
   * - **Tab**: Case Studies
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  case_studies_title: prismic.RichTextField

  /**
   * Section Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Explore Real-Life Examples...
   * - **API ID Path**: homepage.case_studies_description
   * - **Tab**: Case Studies
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  case_studies_description: prismic.RichTextField

  /**
   * Case Studies List field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.case_studies[]
   * - **Tab**: Case Studies
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  case_studies: prismic.GroupField<
    Simplify<HomepageDocumentDataCaseStudiesItem>
  > /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Our Working Process
   * - **API ID Path**: homepage.process_title
   * - **Tab**: Process
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  process_title: prismic.RichTextField

  /**
   * Section Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Step-by-Step Guide...
   * - **API ID Path**: homepage.process_description
   * - **Tab**: Process
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  process_description: prismic.RichTextField

  /**
   * Process Steps field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.process_steps[]
   * - **Tab**: Process
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  process_steps: prismic.GroupField<
    Simplify<HomepageDocumentDataProcessStepsItem>
  > /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Team
   * - **API ID Path**: homepage.team_title
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  team_title: prismic.RichTextField

  /**
   * Section Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Meet the skilled...
   * - **API ID Path**: homepage.team_description
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  team_description: prismic.RichTextField

  /**
   * Team Members field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.team_members[]
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  team_members: prismic.GroupField<
    Simplify<HomepageDocumentDataTeamMembersItem>
  > /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Testimonials
   * - **API ID Path**: homepage.testimonials_title
   * - **Tab**: Testimonials
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_title: prismic.RichTextField

  /**
   * Section Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hear from Our Satisfied Clients...
   * - **API ID Path**: homepage.testimonials_description
   * - **Tab**: Testimonials
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonials_description: prismic.RichTextField

  /**
   * Testimonials List field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[]
   * - **Tab**: Testimonials
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<HomepageDocumentDataTestimonialsItem>
  > /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Our Clients
   * - **API ID Path**: homepage.client_logos_title
   * - **Tab**: Client Logos
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  client_logos_title: prismic.RichTextField

  /**
   * Client Logos field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.client_logos[]
   * - **Tab**: Client Logos
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  client_logos: prismic.GroupField<
    Simplify<HomepageDocumentDataClientLogosItem>
  > /**
   * Section Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contact Us
   * - **API ID Path**: homepage.contact_title
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_title: prismic.RichTextField

  /**
   * Section Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Connect with Us...
   * - **API ID Path**: homepage.contact_description
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_description: prismic.RichTextField

  /**
   * Contact Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.contact_image
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  contact_image: prismic.ImageField<never>

  /**
   * CTA Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Let's make things happen
   * - **API ID Path**: homepage.cta_title
   * - **Tab**: CTA
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField

  /**
   * CTA Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contact us today to learn more...
   * - **API ID Path**: homepage.cta_description
   * - **Tab**: CTA
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField

  /**
   * CTA Button Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get your free proposal
   * - **API ID Path**: homepage.cta_button_text
   * - **Tab**: CTA
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_text: prismic.KeyTextField

  /**
   * CTA Button Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to contact or proposal page
   * - **API ID Path**: homepage.cta_button_link
   * - **Tab**: CTA
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField

  /**
   * CTA Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.cta_image
   * - **Tab**: CTA
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cta_image: prismic.ImageField<never>
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

/**
 * Item in *Pricing → Pricing Tiers*
 */
export interface PricingDocumentDataPricingTiersItem {
  /**
   * Tier Name field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Starter
   * - **API ID Path**: pricing.pricing_tiers[].tier_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tier_name: prismic.KeyTextField

  /**
   * Tier Description field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Best option for personal use & for your individual business
   * - **API ID Path**: pricing.pricing_tiers[].tier_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tier_description: prismic.KeyTextField

  /**
   * Price field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 29
   * - **API ID Path**: pricing.pricing_tiers[].price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField

  /**
   * Features field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add features
   * - **API ID Path**: pricing.pricing_tiers[].features
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features: prismic.RichTextField

  /**
   * Is Popular field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.pricing_tiers[].is_popular
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_popular: prismic.BooleanField

  /**
   * Price Suffix field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /month
   * - **API ID Path**: pricing.pricing_tiers[].price_suffix
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price_suffix: prismic.KeyTextField

  /**
   * Button Text field in *Pricing → Pricing Tiers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Started
   * - **API ID Path**: pricing.pricing_tiers[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField
}

/**
 * Content for Pricing documents
 */
interface PricingDocumentData {
  /**
   * Hero Title field in *Pricing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Designed for business teams like yours
   * - **API ID Path**: pricing.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField

  /**
   * Hero Description field in *Pricing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Here at Positivus we focus on markets...
   * - **API ID Path**: pricing.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField

  /**
   * Pricing Tiers field in *Pricing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.pricing_tiers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pricing_tiers: prismic.GroupField<
    Simplify<PricingDocumentDataPricingTiersItem>
  >
}

/**
 * Pricing document from Prismic
 *
 * - **API ID**: `pricing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PricingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PricingDocumentData>,
    'pricing',
    Lang
  >

/**
 * Content for Services Page documents
 */
interface ServicesPageDocumentData {
  /**
   * Hero Title field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Services
   * - **API ID Path**: services_page.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField

  /**
   * Hero Description field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: At Positivus, we offer a comprehensive range...
   * - **API ID Path**: services_page.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_description: prismic.KeyTextField

  /**
   * CTA Title field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ready to transform your digital presence?
   * - **API ID Path**: services_page.cta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_title: prismic.KeyTextField

  /**
   * CTA Description field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact us today to discuss your digital marketing needs...
   * - **API ID Path**: services_page.cta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_description: prismic.KeyTextField

  /**
   * CTA Button Text field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in touch
   * - **API ID Path**: services_page.cta_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_text: prismic.KeyTextField

  /**
   * CTA Button Link field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /contact
   * - **API ID Path**: services_page.cta_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_link: prismic.KeyTextField
}

/**
 * Services Page document from Prismic
 *
 * - **API ID**: `services_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesPageDocumentData>,
    'services_page',
    Lang
  >

/**
 * Item in *Settings → Navigation Links*
 */
export interface SettingsDocumentDataNavLinksItem {
  /**
   * Label field in *Settings → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link Label
   * - **API ID Path**: settings.nav_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Settings → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link URL
   * - **API ID Path**: settings.nav_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Icon field in *Settings → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>

  /**
   * Link field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Social Link URL
   * - **API ID Path**: settings.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Header Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>

  /**
   * Navigation Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_links: prismic.GroupField<Simplify<SettingsDocumentDataNavLinksItem>>

  /**
   * CTA Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Request a quote
   * - **API ID Path**: settings.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField

  /**
   * CTA Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link URL
   * - **API ID Path**: settings.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Footer Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >

  /**
   * Contact Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: info@positivus.com
   * - **API ID Path**: settings.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField

  /**
   * Contact Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 555-567-8901
   * - **API ID Path**: settings.contact_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_phone: prismic.KeyTextField

  /**
   * Contact Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1234 Main St...
   * - **API ID Path**: settings.contact_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_address: prismic.KeyTextField
  contact_address2: prismic.KeyTextField

  /**
   * Copyright Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2023 Positivus. All Rights Reserved.
   * - **API ID Path**: settings.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

/**
 * Item in *Social Media Marketing → Service Icons*
 */
export interface SocialMediaMarketingDocumentDataServiceIconsItem {
  /**
   * Icon Image field in *Social Media Marketing → Service Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.service_icons[].icon_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_image: prismic.ImageField<never>

  /**
   * Icon Label field in *Social Media Marketing → Service Icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Strategy
   * - **API ID Path**: social_media_marketing.service_icons[].icon_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_label: prismic.KeyTextField
}

/**
 * Item in *Social Media Marketing → Service Detail Sections*
 */
export interface SocialMediaMarketingDocumentDataServiceSectionsItem {
  /**
   * Section Title field in *Social Media Marketing → Service Detail Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Strategy
   * - **API ID Path**: social_media_marketing.service_sections[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField

  /**
   * Section Description field in *Social Media Marketing → Service Detail Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We design and develop meaningful strategies...
   * - **API ID Path**: social_media_marketing.service_sections[].section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField

  /**
   * Section Features field in *Social Media Marketing → Service Detail Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add features as list items
   * - **API ID Path**: social_media_marketing.service_sections[].section_features
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_features: prismic.RichTextField

  /**
   * Section Image field in *Social Media Marketing → Service Detail Sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.service_sections[].section_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  section_image: prismic.ImageField<never>
}

/**
 * Item in *Social Media Marketing → Case Studies*
 */
export interface SocialMediaMarketingDocumentDataCaseStudiesItem {
  /**
   * Case Study Image field in *Social Media Marketing → Case Studies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.case_studies[].case_study_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  case_study_image: prismic.ImageField<never>

  /**
   * Case Study Name field in *Social Media Marketing → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: McDermott Will & Emery
   * - **API ID Path**: social_media_marketing.case_studies[].case_study_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_study_name: prismic.KeyTextField

  /**
   * Category field in *Social Media Marketing → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: LEGAL
   * - **API ID Path**: social_media_marketing.case_studies[].case_study_category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_study_category: prismic.KeyTextField

  /**
   * Case Study Link field in *Social Media Marketing → Case Studies*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add link
   * - **API ID Path**: social_media_marketing.case_studies[].case_study_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  case_study_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Item in *Social Media Marketing → Client Logos*
 */
export interface SocialMediaMarketingDocumentDataClientLogosItem {
  /**
   * Client Logo field in *Social Media Marketing → Client Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.client_logos[].client_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  client_logo: prismic.ImageField<never>

  /**
   * Client Name field in *Social Media Marketing → Client Logos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Client Name
   * - **API ID Path**: social_media_marketing.client_logos[].client_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField
}

/**
 * Content for Social Media Marketing documents
 */
interface SocialMediaMarketingDocumentData {
  /**
   * Hero Title field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Top Line Growth Through Enhanced Digital Presence
   * - **API ID Path**: social_media_marketing.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField

  /**
   * Hero Description field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Technology makes us fast. Empathy makes us human...
   * - **API ID Path**: social_media_marketing.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField

  /**
   * Hero Button Text field in *Social Media Marketing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Let's connect
   * - **API ID Path**: social_media_marketing.hero_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_button_text: prismic.KeyTextField

  /**
   * Hero Button Link field in *Social Media Marketing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add link
   * - **API ID Path**: social_media_marketing.hero_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  hero_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Hero Image field in *Social Media Marketing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>

  /**
   * Philosophy Title field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Tech + Human Empathy = Creativity
   * - **API ID Path**: social_media_marketing.philosophy_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  philosophy_title: prismic.RichTextField

  /**
   * Philosophy Description field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We leverage our deep understanding...
   * - **API ID Path**: social_media_marketing.philosophy_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  philosophy_description: prismic.RichTextField

  /**
   * Services Section Title field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Digital marketing services
   * - **API ID Path**: social_media_marketing.services_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  services_title: prismic.RichTextField

  /**
   * Service Icons field in *Social Media Marketing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.service_icons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_icons: prismic.GroupField<
    Simplify<SocialMediaMarketingDocumentDataServiceIconsItem>
  >

  /**
   * Service Detail Sections field in *Social Media Marketing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.service_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_sections: prismic.GroupField<
    Simplify<SocialMediaMarketingDocumentDataServiceSectionsItem>
  >

  /**
   * Partner Banner Text Line 1 field in *Social Media Marketing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: For social media marketing
   * - **API ID Path**: social_media_marketing.partner_text_line1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_text_line1: prismic.KeyTextField

  /**
   * Partner Banner Text Line 2 field in *Social Media Marketing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: connect with our partner
   * - **API ID Path**: social_media_marketing.partner_text_line2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_text_line2: prismic.KeyTextField

  /**
   * Partner Logo field in *Social Media Marketing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.partner_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  partner_logo: prismic.ImageField<never>

  /**
   * Partner Link field in *Social Media Marketing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add partner link
   * - **API ID Path**: social_media_marketing.partner_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  partner_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Case Studies Title field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Digital marketing case studies
   * - **API ID Path**: social_media_marketing.case_studies_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  case_studies_title: prismic.RichTextField

  /**
   * Case Studies field in *Social Media Marketing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.case_studies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  case_studies: prismic.GroupField<
    Simplify<SocialMediaMarketingDocumentDataCaseStudiesItem>
  >

  /**
   * CTA Title field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Meaningful work. Outstanding results.
   * - **API ID Path**: social_media_marketing.cta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField

  /**
   * CTA Description field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Award-winning digital development company...
   * - **API ID Path**: social_media_marketing.cta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField

  /**
   * CTA Button Text field in *Social Media Marketing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Let's connect
   * - **API ID Path**: social_media_marketing.cta_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_text: prismic.KeyTextField

  /**
   * CTA Button Link field in *Social Media Marketing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add link
   * - **API ID Path**: social_media_marketing.cta_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >

  /**
   * Clients Section Title field in *Social Media Marketing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: You are in great company
   * - **API ID Path**: social_media_marketing.clients_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  clients_title: prismic.RichTextField

  /**
   * Client Logos field in *Social Media Marketing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_marketing.client_logos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  client_logos: prismic.GroupField<
    Simplify<SocialMediaMarketingDocumentDataClientLogosItem>
  >
}

/**
 * Social Media Marketing document from Prismic
 *
 * - **API ID**: `social_media_marketing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaMarketingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialMediaMarketingDocumentData>,
    'social_media_marketing',
    Lang
  >

/**
 * Item in *Use Cases → Solution Cards*
 */
export interface UseCasesDocumentDataSolutionCardsItem {
  /**
   * Icon field in *Use Cases → Solution Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.solution_cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>

  /**
   * Description field in *Use Cases → Solution Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.solution_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField

  /**
   * Background Color field in *Use Cases → Solution Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: use_cases.solution_cards[].background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<'primary' | 'gray' | 'white', 'filled'>
}

/**
 * Content for Use Cases documents
 */
interface UseCasesDocumentData {
  /**
   * Hero Logo field in *Use Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.hero_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_logo: prismic.ImageField<never>

  /**
   * Hero Subheading field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Easly Partners with HawkSEM...
   * - **API ID Path**: use_cases.hero_subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_subheading: prismic.RichTextField

  /**
   * Hero Heading field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CAPITAL-AS-A-SERVICE...
   * - **API ID Path**: use_cases.hero_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_heading: prismic.RichTextField

  /**
   * Description Text field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.description_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_text: prismic.RichTextField

  /**
   * Goal Title field in *Use Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Goal
   * - **API ID Path**: use_cases.goal_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  goal_title: prismic.KeyTextField

  /**
   * Goal Description field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.goal_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  goal_description: prismic.RichTextField

  /**
   * Challenge Title field in *Use Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Challenge
   * - **API ID Path**: use_cases.challenge_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  challenge_title: prismic.KeyTextField

  /**
   * Challenge Description field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.challenge_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_description: prismic.RichTextField

  /**
   * Challenge Image field in *Use Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.challenge_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  challenge_image: prismic.ImageField<never>

  /**
   * Results Title field in *Use Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Results
   * - **API ID Path**: use_cases.results_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  results_title: prismic.KeyTextField

  /**
   * Results List field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.results_list
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  results_list: prismic.RichTextField

  /**
   * Results Image field in *Use Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.results_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  results_image: prismic.ImageField<never>

  /**
   * Solution Cards field in *Use Cases*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.solution_cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  solution_cards: prismic.GroupField<
    Simplify<UseCasesDocumentDataSolutionCardsItem>
  >

  /**
   * Solution Title field in *Use Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Solution
   * - **API ID Path**: use_cases.solution_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  solution_title: prismic.KeyTextField

  /**
   * Solution Description field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.solution_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_description: prismic.RichTextField

  /**
   * Solution Image field in *Use Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.solution_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  solution_image: prismic.ImageField<never>

  /**
   * Impact Title field in *Use Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Impact
   * - **API ID Path**: use_cases.impact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_title: prismic.KeyTextField

  /**
   * Impact Description field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.impact_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_description: prismic.RichTextField

  /**
   * Impact Image field in *Use Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.impact_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  impact_image: prismic.ImageField<never>

  /**
   * CTA Title field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.cta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_title: prismic.RichTextField

  /**
   * CTA Description field in *Use Cases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.cta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_description: prismic.RichTextField

  /**
   * CTA Button Text field in *Use Cases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.cta_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_text: prismic.KeyTextField

  /**
   * CTA Button Link field in *Use Cases*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: use_cases.cta_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >
}

/**
 * Use Cases document from Prismic
 *
 * - **API ID**: `use_cases`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UseCasesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<UseCasesDocumentData>,
    'use_cases',
    Lang
  >

export type AllDocumentTypes =
  | AboutDocument
  | BlogPostDocument
  | HomepageDocument
  | PricingDocument
  | ServicesPageDocument
  | SettingsDocument
  | SocialMediaMarketingDocument
  | UseCasesDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataTagsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataServicesItem,
      HomepageDocumentDataCaseStudiesItem,
      HomepageDocumentDataProcessStepsItem,
      HomepageDocumentDataTeamMembersItem,
      HomepageDocumentDataTestimonialsItem,
      HomepageDocumentDataClientLogosItem,
      PricingDocument,
      PricingDocumentData,
      PricingDocumentDataPricingTiersItem,
      ServicesPageDocument,
      ServicesPageDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavLinksItem,
      SettingsDocumentDataSocialLinksItem,
      SocialMediaMarketingDocument,
      SocialMediaMarketingDocumentData,
      SocialMediaMarketingDocumentDataServiceIconsItem,
      SocialMediaMarketingDocumentDataServiceSectionsItem,
      SocialMediaMarketingDocumentDataCaseStudiesItem,
      SocialMediaMarketingDocumentDataClientLogosItem,
      UseCasesDocument,
      UseCasesDocumentData,
      UseCasesDocumentDataSolutionCardsItem,
      AllDocumentTypes,
    }
  }
}
